# set True if testing for naviagtion to  silo 
testing : False

wait_time_ms: 1000 

# Location of silo w.r.t origin at Y junction
# y co-oridinate of each silo = 4.164
silo_one: [1.50, -2.80]


silo_two: [0.75, -2.80]


silo_three: [0.00, -2.80]


silo_four: [-0.75, -2.80]

silo_five: [-1.50, -2.80]

