# Define robot locations as [x, y, theta]
location_1: [1.0,-0.50,0.0]

location_2: [1.0,-1.0,0.0]

location_3: [1.50,-1.0,0.0]

location_4: [1.50,-0.50,0.00]
order: 10

# Location of silo w.r.t origin at Y junction
# X co-oridinate of each silo = 4.164
silo_one: [-3.264, -1.5]
silo_two: [-3.500, -0.500]
silo_three: [-3.264, 0.0]
silo_four: [-3.264, 0.75]
silo_five: [-3.264, 1.5]