# set True if testing for naviagtion to  silo 
testing : True

# Location of silo w.r.t origin at Y junction
# y co-oridinate of each silo = 4.164
silo_one: [1.50, -3.20]


silo_two: [0.75, -3.20]


silo_three: [0.00, -3.20]


silo_four: [-0.75, -3.20]

silo_five: [-1.50, -3.20]

