# Define robot locations as [x, y, theta]
location_1: [1.0,-0.50,0.0]

location_2: [1.0,-1.0,0.0]

location_3: [1.50,-1.0,0.0]

location_4: [1.50,-0.50,0.00]
order: 10

# Location of silo w.r.t origin at Y junction
# y co-oridinate of each silo = 4.164
silo_one: [1.50, -3.30]
silo_two: [0.90, -3.30]
silo_three: [0.00, -3.30]
silo_four: [-0.90, -3.30]
silo_five: [-1.50, -3.30]